const movies=[
{title:"Starlight Protocol",genre:"Sci-Fi • Action",lang:"English",duration:132,rating:"8.7/10",img:"images/starlight.svg"},
{title:"Midnight Mumbai",genre:"Drama • Thriller",lang:"Hindi",duration:128,rating:"8.3/10",img:"images/midnight.svg"},
{title:"Skybound",genre:"Adventure • Family",lang:"English",duration:116,rating:"8.1/10",img:"images/skybound.svg"},
{title:"Love in Monsoon",genre:"Romance • Drama",lang:"Hindi",duration:121,rating:"7.9/10",img:"images/monsoon.svg"},
{title:"The Last Signal",genre:"Mystery • Sci-Fi",lang:"English",duration:140,rating:"8.5/10",img:"images/signal.svg"},
{title:"Laughing Street",genre:"Comedy",lang:"Hindi",duration:109,rating:"7.8/10",img:"images/laughing.svg"}];
const times=["10:00 AM","1:30 PM","5:00 PM","8:30 PM"],prices=[180,220,250,280];let selectedShow=-1,selected=new Set(),movieIndex=0;
const grid=document.getElementById("movieGrid");
movies.forEach((m,i)=>grid.innerHTML+=`<article class="card"><div class="poster"><img src="${m.img}"><div class="rating">★ ${m.rating}</div></div><div class="body"><span class="tag">${m.lang}</span><span class="tag">${m.duration} min</span><h3>${m.title}</h3><p>${m.genre}</p><a class="view" href="#" onclick="openMovie(${i});return false">View Shows →</a></div></article>`);
function openMovie(i){movieIndex=i;selectedShow=-1;selected.clear();document.getElementById("modalContent").innerHTML=`<p class="eyebrow">NOW BOOKING</p><h2>${movies[i].title}</h2><p>${movies[i].genre} • ${movies[i].lang} • ${movies[i].duration} min</p><h3>Select showtime</h3><div class="show-list">${times.map((t,j)=>`<button class="show" onclick="chooseShow(${j})">${t}<br><small>₹${prices[j]}</small></button>`).join("")}</div><div id="seatArea"></div>`;document.getElementById("modal").classList.add("show")}
function chooseShow(j){selectedShow=j;selected.clear();renderSeats()}
function bookingKey(){return "moviehub_bookings"}
function getBookings(){return JSON.parse(localStorage.getItem(bookingKey())||"[]")}
function renderSeats(){let bookings=getBookings().filter(b=>b.movie===movieIndex&&b.show===selectedShow);let occupied=new Set(bookings.filter(b=>b.status==="CONFIRMED").flatMap(b=>b.seats));let html=`<h3>Select seats</h3><div class="screen">SCREEN</div><div class="seats">`;for(let r=1;r<=6;r++)for(let c=1;c<=10;c++){let id=String.fromCharCode(64+r)+c;let cls=occupied.has(id)?"seat occ":selected.has(id)?"seat sel":"seat";html+=`<button class="${cls}" ${occupied.has(id)?"disabled":`onclick="toggleSeat('${id}')"`}>${id}</button>`}html+=`</div><div class="summary"><strong>${selected.size} seat(s) • ₹${selected.size*prices[selectedShow]}</strong><button class="primary" onclick="confirmBooking()">Confirm Booking</button></div>`;document.getElementById("seatArea").innerHTML=html}
function toggleSeat(id){selected.has(id)?selected.delete(id):selected.add(id);renderSeats()}
function confirmBooking(){if(selectedShow<0)return alert("Select a showtime.");if(!selected.size)return alert("Select at least one seat.");let code="MH-"+Math.random().toString(36).substring(2,10).toUpperCase();let b={code,movie:movieIndex,show:selectedShow,seats:[...selected].sort(),total:selected.size*prices[selectedShow],status:"CONFIRMED",created:new Date().toLocaleString()};let arr=getBookings();arr.push(b);localStorage.setItem(bookingKey(),JSON.stringify(arr));showTicket(b)}
function showTicket(b){let m=movies[b.movie];document.getElementById("modalContent").innerHTML=`<div class="confirm"><div style="font-size:45px;color:#3b9b54">✓</div><p class="eyebrow">BOOKING CONFIRMED</p><h2>Your ticket is ready!</h2><img src="${m.img}" style="width:90px;height:120px;object-fit:cover;border-radius:10px"><h3>${m.title}</h3><p>${times[b.show]} • ${b.seats.join(", ")}</p><p>Total: ₹${b.total}</p><div class="code">${b.code}</div><button class="primary" onclick="closeModal()">Done</button></div>`}
function openCancel(){document.getElementById("modalContent").innerHTML=`<p class="eyebrow">MANAGE BOOKING</p><h2>Cancel your ticket</h2><p>Enter your booking code.</p><input id="cancelCode" class="input" placeholder="MH-XXXXXXXX"><button class="primary danger" onclick="cancelBooking()">Cancel Ticket</button><div id="cancelMsg" style="margin-top:15px"></div>`;document.getElementById("modal").classList.add("show")}
function cancelBooking(){let code=document.getElementById("cancelCode").value.trim().toUpperCase(),arr=getBookings(),b=arr.find(x=>x.code===code);if(!b)return document.getElementById("cancelMsg").textContent="Booking not found.";if(b.status==="CANCELLED")return document.getElementById("cancelMsg").textContent="Already cancelled.";b.status="CANCELLED";localStorage.setItem(bookingKey(),JSON.stringify(arr));document.getElementById("cancelMsg").innerHTML="<b>✓ Booking cancelled successfully.</b>"}
function closeModal(){document.getElementById("modal").classList.remove("show")}
document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
